workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: always

stages:
  - build-app
  - test
  - build-docker-image

build-app:
  stage: build-app
  tags:
    - docker
  image: node:20-slim
  script:
    - cd backend
    - npm i
    - npm run build
  artifacts:
    paths:
      - backend/dist
      - backend/package.json
      - backend/package-lock.json

test:
  stage: test
  tags:
    - docker
  image: node:20-slim
  needs:
    - job: build-app
      artifacts: true
  script:
    - cd backend
    - npm ci
    - npm run test:dist

build-and-docker-image:
  stage: build-docker-image
  tags:
    - docker
  script:
    - cd backend
    - docker build -t localhost:5000/backend:1.0.0 .
    - docker push localhost:5000/backend:1.0.0