workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: always

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  script:
    - cd backend
    - docker build -t registry:5000/backend:1.0.0 .

test:
  stage: test
  tags:
    - docker
  image: node:20-slim
  script:
    - cd backend
    - npm i
    - npm run test
