services:
  front:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "8251:80"
    healthcheck:
      interval: 5s
      timeout: 2s
      retries: 2
      start_period: 2s
    depends_on:
      backend:
        condition: service_healthy
  redis:
    image: redis:8.6.2-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      start_period: 5s
  db:
    image: postgres:18.3-alpine3.23
    volumes:
      - ./db_data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=pswd
      - POSTGRES_USER=usr
      - POSTGRES_DB=default_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U usr -d default_db"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "8512:3001"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  node-exporter:
    image: prom/node-exporter:master
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /:/host:ro
    command:
      - '--path.rootfs=/host'
    networks:
      - monitor-net
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    privileged: true
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitor-net
    devices:
      - /dev/kmsg # Помогает cAdvisor корректно собирать статистику
  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/prometheus.yml:ro
    command: 
      - '--config.file=/prometheus.yml'
    depends_on:
      - cadvisor
      - node-exporter
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3005:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - monitor-net

  registry:
    image: registry:2.8
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - "registry_data:/var/lib/registry"

  docker-dind:
    image: docker:27-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    command: ["--insecure-registry", "registry:5000"]
    volumes:
      - jenkins_data:/var/jenkins_home
    dns:
      - 8.8.8.8
      - 1.1.1.1

  jenkins:
    build: ./jenkins/
    ports:
      - "8080:8080"
    environment:
      - DOCKER_HOST=tcp://docker-dind:2375
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/ref/jenkins.yaml
    volumes:
      - jenkins_data:/var/jenkins_home
      - ./jenkins/jenkins.yaml:/usr/share/jenkins/ref/jenkins.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - monitor-net
    depends_on:
        - docker-dind
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  monitor-net:
    driver: bridge

volumes:
  jenkins_data:
  jenkins_docker_certs:
  registry_data:
