stages:
  - delivery
include:
  - local: '.gitlab/template.yml'

delivery-backend:
    stage: delivery
    tags:
      - docker
    script:
    - cd backend
    - cp $compose_project_backend_env .env
    - docker build -t localhost:5000/backend:1.0.0 .
    - docker push localhost:5000/backend:1.0.0