stages:
  - deploy-backend

.rules_backend_deploy:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == "main"'
      variables:
        DEPLOY_ENV: "prod"
        BACKEND_OUT_PORT: "$BACKEND_OUT_PORT_PROD"
      when: manual

    - if: '$CI_COMMIT_BRANCH == "main"'
      variables:
        DEPLOY_ENV: "prod"
        BACKEND_OUT_PORT: "$BACKEND_OUT_PORT_PROD"
      changes:
        - backend/**/*
      when: manual

    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == "develop"'
      variables:
        DEPLOY_ENV: "develop"
        BACKEND_OUT_PORT: "$BACKEND_OUT_PORT_DEV"
      when: manual

    - if: '$CI_COMMIT_BRANCH == "develop"'
      variables:
        DEPLOY_ENV: "develop"
        BACKEND_OUT_PORT: "$BACKEND_OUT_PORT_DEV"
      changes:
        - backend/**/*
      when: manual

    - when: never

deploy-backend:
  stage: deploy-backend
  tags:
    - docker
  extends: .rules_backend_deploy
  script:
    - echo "ENV SET"
    - echo "---------------------------------------------------"
    - cd "$CI_PROJECT_DIR"
    - cp $compose_project_backend_env backend/.env
    - cp $compose_project_frontend_env frontend/.env
    - cp $compose_project_env .env
    - echo "BACKEND_PORT=$BACKEND_OUT_PORT" >> .env
    - echo "---------------------------------------------------\n\n"
    - echo "DEPLOY"
    - echo "---------------------------------------------------"
    - docker compose -f docker-compose-gitlab.yml pull backend
    - docker compose -f docker-compose-gitlab.yml up -d --force-recreate --no-deps backend
    - echo "---------------------------------------------------"

  environment:
    name: $DEPLOY_ENV
    url: http://localhost:$BACKEND_OUT_PORT
